<?php namespace App\Http\Controllers;

use Session;
use Request;
use DB;
use CRUDbooster;
use Illuminate\Support\Facades\Log;

class AdminCmsUsersController extends CBExtendController {


	public function cbInit() {
		# START CONFIGURATION DO NOT REMOVE THIS LINE
		$this->table               = 'cms_users';
		$this->primary_key         = 'id';
		$this->title_field         = "name";
		$this->button_action_style = 'button_icon_text';
		$this->button_import 	   = FALSE;	
		$this->button_export 	   = FALSE;	
		# END CONFIGURATION DO NOT REMOVE THIS LINE
	
		# START COLUMNS DO NOT REMOVE THIS LINE
		$this->col = array();
		$this->col[] = array("label"=>"Tên","name"=>"name");
        $this->col[] = array("label"=>"Email","name"=>"email");
        $this->col[] = array("label"=>"Mã nhân viên","name"=>"employee_code");
//        $this->col[] = array("label"=>"Kho hàng","name"=>"stock_id","join"=>"gold_stocks,name");
		$this->col[] = array("label"=>"Vai trò","name"=>"id_cms_privileges","join"=>"cms_privileges,name");
		$this->col[] = array("label"=>"Ảnh đại diện","name"=>"photo","image"=>1);
		# END COLUMNS DO NOT REMOVE THIS LINE

		# START FORM DO NOT REMOVE THIS LINE
		$this->form = array(); 		
		$this->form[] = array("label"=>"Tên","name"=>"name",'required'=>true,'validation'=>'required|alpha_spaces|min:3','width'=>'col-sm-4',"help"=>"Tên hiển thị");
		$this->form[] = array("label"=>"Email","name"=>"email",'required'=>true,'type'=>'email','validation'=>'required|email|unique:cms_users,email,'.CRUDBooster::getCurrentId(),'width'=>'col-sm-4',"help"=>"Dùng để đăng nhập");
        $this->form[] = array("label"=>"Mã nhân viên","name"=>"employee_code",'width'=>'col-sm-4',"help"=>"Mã nhân viên sẽ xuất hiện trong báo cáo bán hàng");
        $this->form[] = array('label'=>'Kho hàng','name'=>'stock_id','type'=>'select2','width'=>'col-sm-4','datatable'=>'gold_stocks,name');
//        $this->form[] = ['label'=>'Kho hàng','type'=>'select2','datatable'=>'gold_stocks,name','relationship_table'=>'gold_stocks_cms_users'];
        $this->form[] = array("label"=>"Ảnh đại diện","name"=>"photo","type"=>"upload","help"=>"Kích thước được đề xuất là 200x200 px",'required'=>true,'validation'=>'required|image|max:1000','resize_width'=>200,'resize_height'=>200,'width'=>'col-sm-4');
		$this->form[] = array("label"=>"Vài trò","name"=>"id_cms_privileges","type"=>"select","datatable"=>"cms_privileges,name",'required'=>true,'width'=>'col-sm-4');
		$this->form[] = array("label"=>"Mật khẩu","name"=>"password","type"=>"password",'width'=>'col-sm-4',"help"=>"Vui lòng để trống nếu bạn không muốn đổi mật khẩu");
		# END FORM DO NOT REMOVE THIS LINE
				
	}
    public function getAdd()
    {
        $view = parent::getAdd(); // TODO: Change the autogenerated stub
//        Log::debug('$view = '.$view);

        $view = str_replace('name="stock_id"', 'name="stock_id[]" multiple="multiple"', $view);
        return $view;
    }

    public function getEdit($id)
    {
        $view = parent::getEdit($id); // TODO: Change the autogenerated stub
        $view = str_replace('name="stock_id"', 'name="stock_id[]" multiple="multiple"', $view);
        $user = DB::table('cms_users as U')
            ->where('U.id', $id)
            ->first();
        if($user){
            $view = str_replace("$('#stock_id').select2();", "$('#stock_id').select2().val([".$user->stock_id."]).trigger('change');", $view);
        }
        // Log::debug('$view = '.$view);
        return $view;
    }

    public function hook_before_add(&$arr)
    {
        $arr['stock_id'] = join(',', $arr['stock_id']);
    }

    public function hook_before_edit(&$arr, $id)
    {
        // Log::debug('$arr = ', $arr);
        $arr['stock_id'] = join(',', $arr['stock_id']);
    }

    public function getProfile() {

		$this->button_addmore = FALSE;
		$this->button_cancel  = FALSE;
		$this->button_show    = FALSE;			
		$this->button_add     = FALSE;
		$this->button_delete  = FALSE;	
		$this->hide_form 	  = ['id_cms_privileges'];

		$data['page_title'] = trans("crudbooster.label_button_profile");
		$data['row']        = CRUDBooster::first('cms_users',CRUDBooster::myId());		
		$this->cbView('crudbooster::default.form',$data);				
	}
}
